### ISSUE TITLE
Socketwatcher `node-gyp rebuild` failure

### ISSUE THREAD

**Issue by ghost** [skepticfx/arpjs#10]
Trying to install using:
npm install arpjs --save

Using Windows 10,
Node v7.4.0,
NPM v4.0.5

Thanks.

**Comment by roccomuso** [comment]
arpjs is not yet tested on windows.
Btw could you paste the whole stack trace error?
Moreover, have you installed the libpcap dependency for windows?

**Comment by ghost** [comment]
Sorry, did not read the README. Closing.
