### ISSUE TITLE
Install failed node v10

### ISSUE THREAD

**Issue by realdennis** [skepticfx/arpjs#12]
```
$ git clone https://github.com/skepticfx/arpjs
$ cd arpjs/
$ npm install 
```

--
<details> <summary>Build failed in socket_watcher</summary>

```
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp:77:8: warning: 'MakeCallback' is deprecated
      [-Wdeprecated-declarations]
  Nan::MakeCallback(watcher->handle(), callback, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../socket_watcher.cpp:104:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance());
                              ~~~~~~^~~~~~~~~~~

```

</details>

--

Node version: v10.4
NPM version:  v6.1.0
Compiler version: 
Apple LLVM version 10.0.0 (clang-1000.10.25.5)
Target: x86_64-apple-darwin17.6.0

I found this issue when I install [kickthemout](https://github.com/roccomuso/kickthemout), and it depend on arpjs.

I thought the root cause is `socketwatcher` [like this?](https://github.com/btrask/node-socketwatcher/issues/18) ?

**Comment by roccomuso** [comment]
Yeah, in Node 10 that is deprecated, does it work? those are just warnings.
(if not, try to downgrade your node version).

**Comment by realdennis** [comment]
@roccomuso 
When I downgrade node version to v6, also build failed cause the node-gyp version. (maybe socketwatcher depend old node-gyp version this [issue](https://github.com/nodejs/node-gyp/issues/1464) ) 

`socketwatcher` depend on `nan@^2.0.9` and nan also depend on `node-gyp@~3.6.2`, I thought it was a issue chain ...

**Comment by mkormendy** [comment]
How can we get this working on Node v10?

**Comment by roccomuso** [comment]
@mkormendy the workaround doesn't work for you?

**Comment by mkormendy** [comment]
This error occurs in a repo that uses this package as a dependency. (https://github.com/homespun/homebridge-platform-ring-video-doorbell)

Looks like I'm going to have to fork it and modify the package.json to use a different dependency.

**Comment by roccomuso** [comment]
That repo doesn't use `arpjs` in his dependencies (neither nested ones). Are you sure?

**Comment by mkormendy** [comment]
It uses the socketwatcher. I'll have to work around that.

**Comment by roccomuso** [comment]
ok, so that should be the place to discuss it. There's already an issue: https://github.com/btrask/node-socketwatcher/issues/18.

**Comment by mkormendy** [comment]
Yes, I tracked that issue to this issue - we're cyclical now.

**Comment by realdennis** [comment]
@mkormendy Looks socketwatcher no longer maintained, node_pcap change the dependency socketwatcher to  [this](https://github.com/bytzdev/node-socketwatcher/commit/d252d3f8c45f565a0a48ebd155d4f9e4666798d9) fork.
But in your repo, it depend on pcap2 not node_pcap?

**Comment by mkormendy** [comment]
Thank you @realdennis!!
I see now that pcap2 is the alias for an unmaintained node-pcap by @andygreenegrass .. which is a fork of the official node_pcap which is still maintained.
I will send a pull-request to the author of the repo that uses node_pcap as it's dependency.

Thanks!

**Comment by realdennis** [comment]
@mkormendy Great! 👍
