### ISSUE TITLE
is dst_mac always set to ff:ff:ff:ff:ff:ff?

### ISSUE THREAD

**Issue by davidchatting** [skepticfx/arpjs#14]
Hi - in Wireshark my ARP packets all have a broadcast destination. In packet.js should pkt.dst also be set to macToArr(pktObj.dst_mac) as pkt.dst_mac is?

Thanks!

**Comment by skepticfx** [comment]
You are right. Thanks for noticing this. Can't imagine we missed this. The master branch has the latest fix.

**Comment by skepticfx** [comment]
@davidchatting Also here is the latest npm package: https://www.npmjs.com/package/arpjs/v/1.2.0

Thanks again!

**Comment by davidchatting** [comment]
Excellent - glad to be of help - thanks for the super useful package!

**Comment by RevealedFrom** [comment]
What is the answer to the question in the title of this issue?

Is dst_mac optional or compulsory?  If latter, is it always ff:ff:ff:ff:ff:ff?

**Comment by skepticfx** [comment]
It’s resolved here. You can configure your dest Mac.
