### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by jpacora** [skepticfx/arpjs#2]
This is not working for me on MacOSX (10.10.3) using Node.js v0.12.2 and trying to spoof an android device.

**Comment by skepticfx** [comment]
Let me try to reproduce this soon and get back to you soon!

**Comment by jpacora** [comment]
The error is on "getmac" module, im using WiFi but (en1) but the "getmac" retrieve the mac of the Ethernet port (en0)

**Comment by skepticfx** [comment]
I see! `getmac` is a little old and it seems like there might be a better way of doing this. I'm working on a fix which should solve this. I'll update the package soon.

**Comment by jpacora** [comment]
Im fixing this, i can make a pull request? 😎

**Comment by skepticfx** [comment]
That would be great! I was working on a solution based on node's `os.networkInterfaces()`.

I'll take your fix though. Thanks for doing this. 

Also, If you're interested in working more on this package I would be happy to add you as a moderator for this repo. May be you an add test cases and make it more robust :) 

Let me know!

**Comment by skepticfx** [comment]
Also, the existing thing works on my macbook without any errors on the versions you mentioned. But `getmac` just isn't reliable, since it parses the shell output.

**Comment by jpacora** [comment]
Maybe a "re-arp" after ARP poison?

**Comment by skepticfx** [comment]
Hmm, that won't be the most optimal solution. Can you tell me the output of the following code on your Mac OSX? 

In the node console, type `os.networkInterfaces()` and let me know how the results look like. We can maybe use that as a starting point to solve this.
