### ISSUE TITLE
Take hostname from arp -a

### ISSUE THREAD

**Issue by jbis9051** [skepticfx/arpjs#31]
In the `arp.table` function can we also return the host name (e.g.`jbis-imac.router.home`)? If the hostname is `?` it wasn't found so maybe store that as `null`?

```
jbis-imac.router.home (192.168.1.159) at XX:XX:XX:XX:XX:XX on en1 ifscope permanent [ethernet]
```

**Comment by melono6** [comment]
https://github.com/skepticfx/arpjs/pull/32

**Comment by skepticfx** [comment]
Thanks for reporting and the PR

**Comment by jbis9051** [comment]
Thanks for adding!

Does the PR also change the question mark to null?

**Comment by skepticfx** [comment]
Thanks. Just did.
https://github.com/skepticfx/arpjs/pull/33/files

The whole code was from a long time ago and am not too happy with the code quality. Will do a rewrite soon.
