### ISSUE TITLE
Avoid console.log

### ISSUE THREAD

**Issue by roccomuso** [skepticfx/arpjs#8]
I'm using this module as a lib in a new project.
I think we should avoid printing log on the _stdout_:
[packet.js:L35](https://github.com/skepticfx/arpjs/blob/master/lib/packet.js#L35)

It would be better to use a module like [visionmedia/debug](https://github.com/visionmedia/debug).

**Comment by roccomuso** [comment]
@skepticfx ;)

**Comment by skepticfx** [comment]
Fixed in https://github.com/skepticfx/arpjs/pull/9
